spring:
  application:
    name: TravelBuddy

  # PostgreSQL datasource configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/travel-buddy
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

  # Hibernate configuration
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate

  data:
    # Redis configuration
    redis:
      host: localhost
      port: 6379

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  flyway:
    locations: classpath:db/migration,classpath:db/seeding
    baseline-on-migrate: true
    ignore-migration-patterns: '*:ignored'
    # out-of-order: true

  # Mail configuration
  mail:
    host: smtp.gmail.com
    port: 587
    username: tiennhat306@gmail.com
    password: gxmfwjgmgunedqgu
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  # Kafka configuration
  kafka:
    bootstrap-servers: pkc-312o0.ap-southeast-1.aws.confluent.cloud:9092   #Kafka broker
    consumer:
      group-id: travel-buddy
#      auto-offset-reset: earliest
#      auto-commit-interval: 1000
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: true
      auto-commit-interval: 1000
    #      enable-auto-commit: true
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    properties:
        security:
          protocol: SASL_SSL
        sasl:
          jaas:
            config: org.apache.kafka.common.security.plain.PlainLoginModule required username='55MC47V3SSVIDS5A' password='LJnt14HHwcMFnoGWhmMDyKbGrACb2eNfYSg9KqWKuE8s31xXCevmhj11YGEbucxL';
          mechanism: PLAIN

# Cloudinary configuration
upload:
  cloudinary:
    url: cloudinary://391937763731862:ltLrIBcRWyusN0JumwtdIuG1MpQ@dvmo7pd7e
    delete-batch-size: 100
    temporary-file:
      delete-interval-ms: 300000
      max-age-ms: 3600000
      initial-delay-ms: -1

auth:
  jwt:
    secret: e4KqcRb1kov5z+4L9afIDrYWUiSAJYF6MLbTqinypNA=
    lifespan: 86400000
    algorithm: HS256
